name: Docker Build and Push

on:
  push:
    #branches: []
    #branches: ["main", "production"]
    branches: ["production"]

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: adsr71/birdid-europe254-v250327-1
  IMAGE_NAME: mfn-berlin/birdid-europe254-v250327-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.ORG_GITHUB_TOKEN }} # Use secret repo secret
          

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
